name: Main Suite

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  # Cancel in-progress runs when a new workflow with the same group name is triggered
  cancel-in-progress: true

jobs:
  build-dockerfile:
    name: Build Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Dockerfile
        run: docker build .

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Monorepo
        uses: ./.github/actions/setup-monorepo

      - name: Build
        run: yarn build

  lint:
    needs: build
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Monorepo
        uses: ./.github/actions/setup-monorepo

      - name: Lint
        run: yarn lint

  type-checking:
    needs: build
    name: Type Checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Monorepo
        uses: ./.github/actions/setup-monorepo

      - name: Type Check
        run: yarn typecheck
